### ISSUE TITLE
remove indentation rules

### ISSUE THREAD

**Issue by bingtsingw** [culur/config-stylelint-v1#67]
There is one indentation rule in `css.ts`
```
rules: {
    indentation: 4
}
```

It should be turned off as `stylelint-config-prettier` does, and relies on `prettier` to format the css, or it may be conflict with `prettier`

**Comment by phamhongphuc** [comment]
@bingtsingw
Sorry for the late reply.

You are right, I forgot about this because I always using `@culur/stylelint-config` together with `@culur/prettier-config`.
In `@culur/prettier-config`, the `tabWidth` property was also set to 4, so it didn't result in a conflict error.

I will check your PR.
Thank you for your help.
